# Generated by Django 5.0.1 on 2024-03-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('matricula', models.IntegerField()),
                ('curso', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=255)),
                ('nome_do_professor', models.TextField(max_length=255)),
                ('codigo', models.IntegerField()),
                ('disciplina', models.TextField(max_length=255)),
            ],
        ),
    ]
